### PR TITLE
Replace yarn with pnpm

### PR DESCRIPTION
**Pull request by uxkjaer**

### CODE REVIEW

**Comment by petermuessig** [comment]
Finally, the builds are green and the local development is working fine! Managing the dependencies properly is extremely important for `pnpm`. `yarn` somehow has gracefully hidden dependency issues. Now, we are ready for **`pnpm`**!

Now, it is time for a review! 👍

**Comment by petermuessig** [comment]
Once OK for all of us, I suggest we go ahead with a *squash and merge*

**Comment by uxkjaer** [comment]
> Once OK for all of us, I suggest we go ahead with a _squash and merge_

Good to go for me 😉

**Review by petermuessig — APPROVED** [review]
LGTM

**Comment by petermuessig** [comment]
Ok, it's live now! THX a lot for your work @uxkjaer! Awesome step forward for the repository! As discussed directly we may create some material for this? Docu, blog post, podcast, ...?

**Comment by petermuessig** [comment]
BTW: the link to the performance benchmarks of the package managers: https://pnpm.io/benchmarks

**Pull request merged**
