### PR TITLE
build(deps): bump xlsx from 0.18.5 to 0.20.3

### PR DESCRIPTION
**Pull request by marianfoo**

### CODE REVIEW

**Comment by petermuessig** [comment]
Hmmm, why do you need this that way? Don't they release to NPM anymore?

**Comment by marianfoo** [comment]
Unfortunately not

**Comment by petermuessig** [comment]
Before uploading your change to make the snapshot tests work again please run:

`pnpm --filter ui5-tooling-modules test:snapshots` 

This creates new snapshots and the test may complete then.

THX

**Comment by marianfoo** [comment]
If you don't use you can remove it

**Comment by petermuessig** [comment]
> If you don't use you can remove it

What do you mean? The tests do not run because of the update of the dependencies as the snapshots (1:1 comparison of the generated files) don't match anymore. In case of changing dependency versions the snapshots must be updated in order the build/test to succeed.

**Review by petermuessig — APPROVED** [review]
OK with me

**Pull request merged**
