### PR TITLE
Fix Absolute Path Error for Third Party Dependencies

### PR DESCRIPTION
**Pull request by Magoli1**
Hey everyone,

this is a fix for #540. It should replace the first forward slash in call cases. Let me know your thoughts 👍🏾 

I will add the change to the changelog, after you are fine with the change.

Best Regards
Robert

### CODE REVIEW

**Comment by vobu** [comment]
@IObert we should definitely add also a test harness/skeleton for the tasks in the same way we started it for the middleware(s) (e.g. https://github.com/ui5-community/ui5-ecosystem-showcase/tree/master/packages/ui5-middleware-cfdestination/test)
this PR seems like an excellent entry point for this :)
do you have time to tacke introducing a test skeleton? want to do it together?

**Comment by IObert** [comment]
Hi, 

the PR looks good to me but I agree with @vobu. We should add some tests at this points. Unfortunately, I don't think I'll have time for this in the next few weeks. 
Would someone volunteer to add such tests to this PR an well?

**Comment by vobu** [comment]
i'll try and whip up something the next days.
@Magoli1: i'll try and push to this PR; if not possible, i'll PR your fork 🧑‍🍳

**Comment by IObert** [comment]
Many thanks @vobu 🥳

**Comment by vobu** [comment]
here we go. @Magoli1 please doublecheck, @IObert please glance-review, then -> allez-hop `squash and merge`

**Comment by vobu** [comment]
sooo, regarding the ci errors:
- UI5 app tests: this looks ok as it's an issue w/ chrome versions and `UIveri5`
- middleware- and tasks-tests: work fine locally; i assume i've outrun @Magoli1's actions quota/limits :) sorry :)

please run the tests 
`yarn workspace ui5-middleware-cfdestination test && yarn workspace ui5-task-zipper test`
locally and let me know your results.

**Comment by IObert** [comment]
LGTM

**Comment by Magoli1** [comment]
@vobu Not sure about the test results here 😢 Locally it also gives me failed tests for ``yarn workspace ui5-task-zipper test``. My personal quota is probably not the problem as I have 2,500 minutes left currently 😁 Maybe the zipfile is not being created correctly? ``Cannot read property 'readEntry' of undefined`` makes me think..

**Comment by vobu** [comment]
so there was an error in `ui5/cli` 2.12.1, see https://github.com/SAP/ui5-tooling/issues/567
downgraded to 2.12.0, now middleware- and task-tests check out fine.
there's still the ui5-app test failing due to the uiveri5-issue - which i'm not going to fix for this task-related PR 🧑‍🍳

**Comment by Magoli1** [comment]
Nice work! LGTM! 🚀

**Comment by Magoli1** [comment]
@vobu Any ETA on when this will be released on NPM? I just saw there is no publishing done via GH Actions
I would love to see this fix in 😁

**Comment by vobu** [comment]
i remote-triggered the (manual) release process already :)

**Pull request merged**
