### PR TITLE
feat(ui5-task-stringreplacer): ignore grafical mime types

### PR DESCRIPTION
**Pull request by dominikfeininger**
Fix in`ui5-task-stringreplacer` like here: https://github.com/ui5-community/ui5-ecosystem-showcase/pull/672

`getMimeInfo function was taken from here: https://github.com/SAP/ui5-server/blob/1ef8437dae4bda90e290122959f80c6dc72e3e00/lib/middleware/MiddlewareUtil.js#L90

### CODE REVIEW

**Comment by dominikfeininger** [comment]
Hi @petermuessig, I need your help please.

Since I wasn't sure what to do about the first failed attempt. I reverted all changes and the tests still fail. Can you please have a look and give me a hint.

Thanks

**Comment by petermuessig** [comment]
Hi @dominikfeininger, I can check later today. The issue is the following:

```
TypeError: Cannot read properties of undefined (reading 'setModel')
	    at fnClass.onInit (webapp/controller/Main.controller.js:8:18)
	    at Object.eval (webapp/test/unit/controller/Main.controller.js:10:18)
	    at Object.sinonSandboxedTest (webapp/resources/sap/ui/thirdparty/sinon.js:[55](https://github.com/ui5-community/ui5-ecosystem-showcase/actions/runs/3948434136/jobs/6758419018#step:9:56)98:39)
	    at Object.sinonAsyncSandboxedTest (webapp/resources/sap/ui/thirdparty/sinon.js:[56](https://github.com/ui5-community/ui5-ecosystem-showcase/actions/runs/3948434136/jobs/6758419018#step:9:57)29:47)
	    at runTest (webapp/resources/sap/ui/thirdparty/qunit-2.js:14[57](https://github.com/ui5-community/ui5-ecosystem-showcase/actions/runs/3948434136/jobs/6758419018#step:9:58):30)
	    at Test.run (webapp/resources/sap/ui/thirdparty/qunit-2.js:1443:6)
	    at webapp/resources/sap/ui/thirdparty/qunit-2.js:1635:12
	    at Object.advance (webapp/resources/sap/ui/thirdparty/qunit-2.js:1120:26)
	    at begin (webapp/resources/sap/ui/thirdparty/qunit-2.js:2811:20)
	    at webapp/resources/sap/ui/thirdparty/qunit-2.js:2771:6
```

Maybe this is related to one of the latest changes of the demo apps. Did you rebase you change on the latest commit? 

BTW: I also thought about creating a common tooling extension for the string replacer rather than having a middleware and a task. Similar like for the `ui5-tooling-modules` and `ui5-tooling-transpile` we could create the `ui5-tooling-stringreplacer` and share the common coding between the task and the middleware. WDYT?

**Comment by petermuessig** [comment]
Hi @dominikfeininger, please rebase your change on the latest `main`. I provided a fix for the OPA5 test to succeed.

BTW: did you think of creating one tooling extension out of the task and the middleware? Interested? We can merge this here, but this would be a small follow-up activity.

**Comment by dominikfeininger** [comment]
@petermuessig yep, I will need some time, but I will give it a shot to refactor both in a single module.

**Review by petermuessig — APPROVED** [review]

**Pull request merged**
