### PR TITLE
Multitenancy config and routing

### PR DESCRIPTION
**Pull request by stefania-santimbrean**

### CODE REVIEW

**Comment by stefania-santimbrean** [comment]
For #519

**Comment by vobu** [comment]
for testing purposes: you could use `nock` https://github.com/nock/nock for mocking a http endpoint, e.g. the target of your multi-tenancy redirect, and send back the expected response(s).

**Comment by vobu** [comment]
hi @stefania-santimbrean - the logic works and the tests check out fine...the latter unfortunately only locally, not in gh action. can you check whether the tests run fine for you locally? and probably you have an eye for spotting the root cause why they don't run through in ci/gh action.

**Comment by stefania-santimbrean** [comment]
@vobu

Tests worked on my local, too. But I had to clone the project on a path which does not have folders with spaces in their name or else line 36 from `boot.test.js` was complaining that it does not resolve the path. I don't know if this is also causing ci/gh action not to run.

But I tried the hack with npm link into the multitenant project for testing and it's throwing me this error in the Terminal logs when I try to access `http://localhost:8080/backend/endpoint`:
```
REQUEST {
  uri: 'http://consumer.localhost:5000/backend/endpoint',
  callback: undefined
}
REQUEST make request http://consumer.localhost:5000/backend/endpoint
internal/streams/legacy.js:61
      throw er; // Unhandled stream error in pipe.
      ^

Error: getaddrinfo ENOTFOUND etm-consumer.localhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'consumer.localhost'
}
```

But if I have have the UI5 Tooling with the cfdestination middleware started and I just access directly in Chrome: `http://consumer.localhost:5000/backend/endpoint` it brings me back data.

Maybe the issue is around line 107 in `cfdestination.js`: `req.pipe(request(url)).pipe(res)`? And maybe this is why it also does not work in ci/gh action? Only the multitenancy test is not working there or all of them?

Or try it with yarn instead of npm? :))

Do you have any suggestions?

**Comment by vobu** [comment]
back after 🏝, will take on the gh action ci/cd issue now

**Comment by vobu** [comment]
@stefania-santimbrean please have a look :) if it looks good to you, i'll merge it - finally :)

**Comment by stefania-santimbrean** [comment]
@vobu thanks for coming back to this :) I'll try it now again

**Comment by stefania-santimbrean** [comment]
@vobu In the meantime I changed my environment a lot so now I started fresh with did `yarn install` in root folder and `yarn test` in packages/ui5-middleware-cfdestination and 1 tests is pending in test/options.test.js and times out eventually:
```
✖ Timed out while running tests

1 tests were pending in test/options.test.js

◌ options › ui5.yaml: no config -> default options apply
```
Am I missing something?

**Comment by vobu** [comment]
> @vobu In the meantime I changed my environment a lot so now I started fresh with did `yarn install` in root folder and `yarn test` in packages/ui5-middleware-cfdestination and 1 tests is pending in test/options.test.js and times out eventually:
> 
> ```
> ✖ Timed out while running tests
> 
> 1 tests were pending in test/options.test.js
> 
> ◌ options › ui5.yaml: no config -> default options apply
> ```
> 
> Am I missing something?

no, i don't think so - if your system is somewhat busy and `ava` (the testrunner) can't allocate enough resources in time, the timeout occurs - try running `yarn test --timeout=1m` and see if that resolves the issue

**Comment by vobu** [comment]
> @vobu I'm also trying now with `yarn link` the middleware usage in a multitenant app.
> 
> The ui5 serve process gets killed if I try to hit an endpoint on localhost:8080 because of `Error: getaddrinfo ENOTFOUND`. But if I try on subdomain.localhost:5000 it works, so the approuter is started in multitenant mode fine. I assume that the redirect from localhost:8080 to subdomain.localhost:5000 needs something more for it to work.
> 
> If I try to add in /etc/hosts subdomain.localhost and try to go to localhost:8080/xsuaaProtectedEndpoint it goes to `subdomain.localhost:5000/login/callback?code=idpCode` ang gives HTTP ERROR 400 and does not reach the backend.
> 
> I'm still looking into this...

it's all complicated, isn't it? :( 
from my perspective, the "whole thing"™ is a multistep approach:
1. `yarn link`| `npm link` the yet unpublished `ui5-middleware-cfdestination` &rarr; ✅ this seems to be working for you
2. modify `/etc/hosts` to resolve a local subdomain, e.g. `127.0.0.1 subdomain.localhost` &rarr; ✅ seems to be working for you as well
2. make sure `ui5 serve` actually runs on `localhost:8080` as the ui5-tooling dynamically allocates a port if 8080 is in use

what somewhat confuses me is that you say
- `localhost:8080` doesn't work
- but `localhost:$port/xsuaaProtectedEndpoint` works and redirects you to the `subdomain.localhost:5000/login/callback?code=idpCode`?

for a working example of authenticating a local ui5 application with a remote BTP idp, check out https://github.com/rsletta/ui5-vscode-local - if you provide a `default-env.json` with valid `VCAP_SERVICES.xsuaa.credentials`, the flow should work.
Note that all the magic lies in `uimodule/index1.html` routed in `xs-app.json` to be available at `http://localhost:8080/index1.html` &rarr; approuter then picks up that route, redirects you the `xsuaa` from `default-env.json` and -upon successful auth-  `index1.html` then client-side redirects you to `localhost:8080/index.html`

**Comment by stefania-santimbrean** [comment]
> > @vobu I'm also trying now with `yarn link` the middleware usage in a multitenant app.
> > The ui5 serve process gets killed if I try to hit an endpoint on localhost:8080 because of `Error: getaddrinfo ENOTFOUND`. But if I try on subdomain.localhost:5000 it works, so the approuter is started in multitenant mode fine. I assume that the redirect from localhost:8080 to subdomain.localhost:5000 needs something more for it to work.
> > If I try to add in /etc/hosts subdomain.localhost and try to go to localhost:8080/xsuaaProtectedEndpoint it goes to `subdomain.localhost:5000/login/callback?code=idpCode` ang gives HTTP ERROR 400 and does not reach the backend.
> > I'm still looking into this...
> 
> it's all complicated, isn't it? :(
> from my perspective, the "whole thing"™ is a multistep approach:
> 
> 1. `yarn link`| `npm link` the yet unpublished `ui5-middleware-cfdestination` → ✅ this seems to be working for you
> 2. modify `/etc/hosts` to resolve a local subdomain, e.g. `127.0.0.1 subdomain.localhost` → ✅ seems to be working for you as well
> 3. make sure `ui5 serve` actually runs on `localhost:8080` as the ui5-tooling dynamically allocates a port if 8080 is in use
> 
> what somewhat confuses me is that you say
> 
> * `localhost:8080` doesn't work
> * but `localhost:$port/xsuaaProtectedEndpoint` works and redirects you to the `subdomain.localhost:5000/login/callback?code=idpCode`?
> 
> for a working example of authenticating a local ui5 application with a remote BTP idp, check out https://github.com/rsletta/ui5-vscode-local - if you provide a `default-env.json` with valid `VCAP_SERVICES.xsuaa.credentials`, the flow should work.
> Note that all the magic lies in `uimodule/index1.html` routed in `xs-app.json` to be available at `http://localhost:8080/index1.html` → approuter then picks up that route, redirects you the `xsuaa` from `default-env.json` and -upon successful auth- `index1.html` then client-side redirects you to `localhost:8080/index.html`

About 3. I can see files at localhost:8080 so it's started on this port (and I also don't have anything else on this port). I think I was not clear when I was saying the localhost:8080 does not work, I meant that If I try a xsuaa protected backend endpoint localhost:8080/endpoint it throws me an error, If I go to index.html it loads the ui files.

If I try the same endpoint on subdomain.localhost:5000/endpoint it works. This xs-app.json and default-env.json configuration which I'm trying was working when in single-tenant mode so it should work also in multi-tenant mode the same with the addition of the correct subdomain in ui5.yaml (and the default-env.json TENANT_HOST_PATTERN property).

Yesterday I tried to find why it's not working and these are my discoveries:

- given that I modify `/etc/hosts` to have also contain `127.0.0.1       subdomain.localhost`
- when I try the xsuaa protected endpoint localhost:8080/endpoint -> in the Network tab: it redirects to `https://subdomain.authentication.eu10.hana.ondemand.com/oauth/authorize?...` which has `302 Found` http status, then redirects to `http://subdomain.localhost:5000/login/callback?code=idpCode` which has status `400 Signature does not match` and it does not return to `localhost:8080/endpoint` or at least to `subdomain.localhost:5000/endpoint`

I was thinking that maybe there is a http header which is different that causes the second one to give a 4xx status and not a 3xx redirect http status, but no luck yet :(

One important mention for the redirect callback is that in the configuration file of the XSUAA service `xs-security.json` I have this section:
```
"oauth2-configuration": {
		"redirect-uris": [
			"https://*.cfapps.eu10.hana.ondemand.com/**",
			"https://*.applicationstudio.cloud.sap/**",
			"http://localhost:5000/**",
			"http://*.localhost:5000/login/callback",
			"http://localhost:8080/**",
		]
	}
```
Which I think should cover what we need, but it might be that my xsuaa service did not get updated to include the redirect to `"http://localhost:8080/**"` or maybe there's something missing here also.

Any suggestions on what else to try are more than welcomed.

Kind regards,
Stefania

P.S. `yarn test --timeout=1m` worked

**Comment by vobu** [comment]
i'm merging the code base for this now - ping @petermuessig as a fix for running the e2e tests are included here
@stefania-santimbrean let's take working on a local multi-tenant setup elsewhere; i suggest another vs code liveshare mob programming session :)

**Pull request merged**
