### PR TITLE
feat(cds-plugin-ui5): use CAP logging, custom formatter using colors, allow log levels

### PR DESCRIPTION
**Pull request by petermuessig**
Supports setting log levels to filter log messages:

```json
"cds": {
  "log": {
    "levels": {
      "cds-plugin-ui5": "warn"
    }
  }
}
```

### CODE REVIEW

**Comment by petermuessig** [comment]
@schiwekM if you are OK with my changes to the PR, we can go ahead and merge and release

**Review by schiwekM — APPROVED** [review]
LGTM & thanks for making the adjustments. Have to agree that with colouring it looks nicer.

Do any tests have to be added for the package?

**Comment by petermuessig** [comment]
The package has no tests yet. Besides my test apps in the showcases there is no auto validation for it. Would be a nice feature to add...

**Comment by petermuessig** [comment]
I'll merge this change now - and the tests can be done separately.

**Comment by petermuessig** [comment]
Release of `0.10.0` is in progress

**Pull request merged**
