### PR TITLE
fix: encoding of full url

### PR DESCRIPTION
**Pull request by sebbi08**
req.path and req.url are already fully encoded so we only need to encode the url parameters to prevent double encoding

closes : https://github.com/ui5-community/ui5-ecosystem-showcase/issues/529

### CODE REVIEW

**Review by treee111 — APPROVED** [review]
Hi @sebbi08,
thanks for providing a fix for the issue! 🥇

I tested your branch/PR on our local setup and the encoding of URL's works for our usecase as in Version 0.7.1.

I'm looking forward to see this PR being merged and published 👍

**Comment by treee111** [comment]
the tests "test:opa5" and "test:opa5-ci" both run successful on my local machine. But there are some errors: BadRequestError and TypeError.

**Comment by petermuessig** [comment]
LGTM 👍

**Comment by petermuessig** [comment]
Just checking why the build fails.

**Comment by vobu** [comment]
> Just checking why the build fails.

fixed in #528 - once that is in (very soon), e2e tests should be working again

**Comment by petermuessig** [comment]
OMG, I missed to submit and release this one here. Will do it now... 😨

**Pull request merged**
