### PR TITLE
feat: Enhance readme

### PR DESCRIPTION
**Pull request by heimwege**
Add information about supported CAP runtime to readme of
- ui5-middleware-cap
- cds-plugin-ui5

### CODE REVIEW

**Comment by heimwege** [comment]
Hey @petermuessig 👋🏻 
As I've fallen into this trap yesterday I thought this information might be helpful for others as well 🐱

**Comment by heimwege** [comment]
I feel innocent w.r.t those failing tests 🙈

**Comment by petermuessig** [comment]
Still wondering where they are coming from - this is more an infrastructural issue here which is related to the pnpm...

**Comment by petermuessig** [comment]
@heimwege can you please rebase your change? I made some update to the GH actions and it should work now!

**Comment by petermuessig** [comment]
THX @heimwege

**Pull request merged**
