### PR TITLE
dev-approuter: improve routes injection and logging

### PR DESCRIPTION
**Pull request by vobu**
this PR introduces two things:
- inserts auto-generated routes _after_ explicitly configured ones in `xs-app.json`
  → this enables to have the CAP backend available "as in CF" via a proxied mountpoint
  before:
  ```jsonc
  {
    authenticationType: 'none',
    source: '/odata/v4/a(/.*)|/odata/v4/b(/.*)',
    destination: 'my-cds-app'
  },
   {
    source: '/backend/(.*)$',
    target: '/$1',
    destination: 'srv_api'
  }
   ```
   this lead to requests to `/backend/odata/v4/...` to not work, b/c of regex interference

  after:
  ```jsonc 
  {
    source: '/backend/(.*)$',
    target: '/$1',
    destination: 'srv_api'
  }
  {
    authenticationType: 'none',
    source: '/odata/v4/a(/.*)|/odata/v4/b(/.*)',
    destination: 'my-cds-app'
  }
   ```
   beautiful `200` on `/backend/odata/v4/...` requests

- logs routes (incl auto-generated) and destinations (incl auto-generated) at startup
  → the developer knows what black magic was weaved

   _before_:
   -nothing-

   _after_:
  ```shell
  [dev-approuter] - running these destinations: [
  {
    name: 'srv_api',
    url: 'http://localhost:4004',
    forwardAuthToken: true
  },
  { name: 'ui', url: 'http://localhost:8080', forwardAuthToken: true },
  {
    Name: 'my-cds-app',
    Authentication: 'NoAuthentication',
    ProxyType: 'Internet',
    Type: 'HTTP',
    URL: 'http://localhost:4004'
  }
  ]

  [dev-approuter] - running these routes: [
    {
      source: '/backend/(.*)$',
      target: '/$1',
      destination: 'srv_api'
    },
    {
      authenticationType: 'none',
      source: '/odata/v4/a(/.*)|/odata/v4/b(/.*)',
      destination: 'my-cds-app'
    }
  ]
  ```

### CODE REVIEW

**Comment by petermuessig** [comment]
@vobu - this introduces a required dependency to`@sap/cds` which I would avoid here. Or did you think about making it optional as the JS code suggests? In this case, please add a `peerDependenciesMeta` section which marks the `@sap/cds` dependency as optional: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#peerdependenciesmeta (recommended to not get @sap/cds installed via this package). Other option would be using the `optionalDependencies` section but this would try to install the dependency and just in case it cannot it will not fail.

**Comment by vobu** [comment]
> @vobu - this introduces a required dependency to`@sap/cds` which I would avoid here. Or did you think about making it optional as the JS code suggests?

yes, that was exactly the intention: use `@sap/cds`'s logger if it's available. Will make it explicit by adding `peerDependenciesMeta` - again what learned, thanks for that!

**Comment by petermuessig** [comment]
@vobu: sorry for bothering you again - please fetch and rebase you change so that we can merge it - resolving the `pnpm-lock.yaml` is too cumbersome... THX

**Review by petermuessig — CHANGES_REQUESTED** [review]
Please rebase to resolve merge conflicts

**Comment by vobu** [comment]
> Please rebase to resolve merge conflicts

this was more ugh than I expected. But done now.

**Comment by vobu** [comment]
> > Please rebase to resolve merge conflicts
> 
> this was more ugh than I expected. But done now.

Hey @petermuessig, this guy https://github.com/ui5-community/ui5-ecosystem-showcase/blob/c6f7ce2a578eb1b3396a6f595b6629e20ee4784a/packages/ui5-tooling-modules/test/util.test.js#L325 is causing trouble…outdated snapshot or real error?

**Comment by vobu** [comment]
> > > Please rebase to resolve merge conflicts
> > 
> > 
> > this was more ugh than I expected. But done now.
> 
> Hey @petermuessig, this guy
> 
> https://github.com/ui5-community/ui5-ecosystem-showcase/blob/c6f7ce2a578eb1b3396a6f595b6629e20ee4784a/packages/ui5-tooling-modules/test/util.test.js#L325
> 
> is causing trouble…outdated snapshot or real error?

answer-to-self: it's the snapshot file. Not DNS. But the snapshot.

**Comment by petermuessig** [comment]
When updating the dependencies of the repository, the snapshots for the ui5-tooling-modules need to be recreated. You can do this via:

`pnpm --filter ui5-tooling-modules test:snapshots`

But I can do so also later and finalize the PR

**Comment by petermuessig** [comment]
Ah no, I see you did it already. Ok, change is green and can be merged

**Review by petermuessig — APPROVED** [review]

**Comment by nicoschoenteich** [comment]
Sweet! Thanks a lot @vobu and @petermuessig! Glad to see the `dev-approuter` is still being used 🙂

**Pull request merged**
